import type { Product, Category } from './types';

export const categories: Category[] = [
  { id: 'cat-1', name: 'Herrenbekleidung', slug: 'mens-clothing', imageId: 'mens-category' },
  { id: 'cat-2', name: 'Damenbekleidung', slug: 'womens-clothing', imageId: 'womens-category' },
  { id: 'cat-3', name: 'Accessoires', slug: 'accessories', imageId: 'accessories-category' },
  { id: 'cat-5', name: 'Schuhe', slug: 'shoes', imageId: 'shoes-category' },
  { id: 'cat-4', name: 'Winterkleidung', slug: 'winter-clothing', imageId: 'winter-category' },
];

export const products: Product[] = [
  // Winter Wear - Men
  {
    id: 'prod-winter-1',
    name: 'Langer Wollmantel von Hugo Boss',
    slug: 'manteau-long-laine-hugo-boss',
    price: 799.00,
    description: 'Ein klassischer langer Mantel aus reiner Schurwolle, der Wärme und eine tadellos elegante Silhouette von Hugo Boss bietet.',
    category: 'winter-clothing',
    images: ['manteau-long-laine-hugo-boss'],
    reviews: [],
  },
  {
    id: 'prod-winter-2',
    name: 'Gesteppte Daunenjacke von Moncler',
    slug: 'doudoune-matelassee-moncler',
    price: 1250.00,
    description: 'Die ikonische Daunenjacke von Moncler, die technische Leistung und alpinen Stil für optimalen Kälteschutz vereint.',
    category: 'winter-clothing',
    images: ['doudoune-matelassee-moncler'],
    reviews: [],
  },
  {
    id: 'prod-winter-3',
    name: 'Arctic Parka von Canada Goose',
    slug: 'parka-arctic-canada-goose',
    price: 1150.00,
    description: 'Entwickelt für die extremsten Klimazonen, ist der Arctic Parka von Canada Goose der Gipfel an Wärme und Haltbarkeit.',
    category: 'winter-clothing',
    images: ['parka-arctic-canada-goose'],
    reviews: [],
  },
  {
    id: 'prod-winter-4',
    name: 'Kaschmirmantel von Loro Piana für Herren',
    slug: 'manteau-cachemire-loro-piana-homme',
    price: 4500.00,
    description: 'Luxus in seiner reinsten Form. Dieser doppelseitige Kaschmirmantel von Loro Piana ist von unvergleichlicher Weichheit und Wärme.',
    category: 'mens-clothing',
    images: ['manteau-cachemire-loro-piana-homme'],
    reviews: [],
  },
  {
    id: 'prod-winter-5',
    name: 'Shearling-Blouson von Saint Laurent',
    slug: 'blouson-shearling-saint-laurent',
    price: 4800.00,
    description: 'Ein kühner Fliegerblouson aus gewachsenem Lammfell von Saint Laurent für einen rockigen und luxuriösen Stil.',
    category: 'mens-clothing',
    images: ['blouson-shearling-saint-laurent'],
    reviews: [],
  },
  {
    id: 'prod-winter-6',
    name: 'Rollkragenpullover aus Merinowolle von Paul Smith',
    slug: 'pull-col-roule-laine-merinos-paul-smith',
    price: 350.00,
    description: 'Ein unverzichtbares Winter-Basic: Dieser Rollkragenpullover aus feiner Merinowolle von Paul Smith ist ebenso weich wie vielseitig.',
    category: 'mens-clothing',
    images: ['pull-col-roule-laine-merinos-paul-smith'],
    reviews: [],
  },
  {
    id: 'prod-winter-7',
    name: 'Gefüttertes Überhemd von Acne Studios für Herren',
    slug: 'surchemise-doublee-acne-studios-homme',
    price: 420.00,
    description: 'Das gefütterte Wollflanell-Überhemd von Acne Studios, perfekt für Lagenlooks in der Übergangszeit mit skandinavischem Touch.',
    category: 'mens-clothing',
    images: ['surchemise-doublee-acne-studios-homme'],
    reviews: [],
  },
  {
    id: 'prod-winter-8',
    name: 'Ärmellose Daunenjacke von Polo Ralph Lauren',
    slug: 'doudoune-sans-manche-polo-ralph-lauren',
    price: 250.00,
    description: 'Leicht und praktisch ist diese ärmellose Daunenjacke ein Klassiker von Polo Ralph Lauren, ideal über einem Pullover oder unter einem Mantel.',
    category: 'winter-clothing',
    images: ['doudoune-sans-manche-polo-ralph-lauren'],
    reviews: [],
  },
  {
    id: 'prod-winter-9',
    name: 'Doppelreihiger Trenchcoat von Burberry',
    slug: 'manteau-trench-double-burberry',
    price: 1990.00,
    description: 'Der ikonische Trenchcoat von Burberry. Ein zeitloses und wetterfestes Stück, Symbol britischer Eleganz.',
    category: 'winter-clothing',
    images: ['manteau-trench-double-burberry'],
    reviews: [],
  },
  {
    id: 'prod-winter-10',
    name: 'Dicker Zopfmusterpullover von Dior Homme',
    slug: 'pull-torsade-epais-dior-homme',
    price: 1100.00,
    description: 'Ein reich texturierter Pullover aus Wolle und Kaschmir, verziert mit klassischen Zopfmustern. Ein Meisterstück von Dior.',
    category: 'mens-clothing',
    images: ['pull-torsade-epais-dior-homme'],
    reviews: [],
  },
  {
    id: 'prod-winter-11',
    name: 'Wasserdichte technische Jacke der TNF Black Series',
    slug: 'veste-technique-impermeable-tnf-black-series',
    price: 650.00,
    description: 'Aus der High-End-Linie von The North Face kombiniert diese Jacke futuristisches Design mit maximalem Schutz vor den Elementen.',
    category: 'winter-clothing',
    images: ['veste-technique-impermeable-tnf-black-series'],
    reviews: [],
  },
  // Winter Wear - Women
  {
    id: 'prod-winter-12',
    name: 'Seiden-Midikleid von Gucci',
    slug: 'robe-midi-en-soie-gucci',
    price: 2500.00,
    description: 'Ein Midikleid aus Seiden-Crêpe von Gucci, verziert mit einem kühnen Druck für maximale Eleganz.',
    category: 'womens-clothing',
    images: ['robe-midi-en-soie-gucci'],
    reviews: [],
  },
  {
    id: 'prod-winter-13',
    name: 'Doppelreihiger Blazer von Balmain',
    slug: 'blazer-croise-balmain',
    price: 2200.00,
    description: 'Der ikonische doppelreihige Balmain-Blazer mit seinen goldenen Knöpfen, ein starkes Stück, das die Silhouette kühn strukturiert.',
    category: 'womens-clothing',
    images: ['blazer-croise-balmain'],
    reviews: [],
  },
  {
    id: 'prod-winter-14',
    name: 'Kaschmir-Rollkragenpullover von Loro Piana für Damen',
    slug: 'pull-col-roule-cachemire-loro-piana-femme',
    price: 1800.00,
    description: 'Die Quintessenz von Luxus und Komfort. Dieser Rollkragenpullover von Loro Piana aus reinem Kaschmir ist wie eine zweite Haut.',
    category: 'womens-clothing',
    images: ['pull-col-roule-cachemire-loro-piana-femme'],
    reviews: [],
  },
  {
    id: 'prod-winter-15',
    name: 'Weite Wollhose von Max Mara',
    slug: 'pantalon-large-en-laine-max-mara',
    price: 650.00,
    description: 'Eine weit geschnittene Hose mit perfekter Passform aus fließender Wolle von Max Mara für einen schicken und lässigen Look.',
    category: 'womens-clothing',
    images: ['pantalon-large-en-laine-max-mara'],
    reviews: [],
  },
  {
    id: 'prod-winter-16',
    name: 'Premium Slim-Jeans von Diesel',
    slug: 'jean-slim-premium-diesel',
    price: 280.00,
    description: 'Eine Slim-Jeans mit perfekter Passform und dezenter Waschung aus hochwertigem Denim von Diesel.',
    category: 'womens-clothing',
    images: ['jean-slim-premium-diesel'],
    reviews: [],
  },
  {
    id: 'prod-winter-17',
    name: 'Bedruckte Seidenbluse von Saint Laurent',
    slug: 'chemisier-en-soie-imprimee-saint-laurent',
    price: 1350.00,
    description: 'Eleganz und Modernität treffen in dieser fließenden Seidenbluse mit exklusivem Saint Laurent-Druck aufeinander.',
    category: 'womens-clothing',
    images: ['chemisier-en-soie-imprimee-saint-laurent'],
    reviews: [],
  },
  {
    id: 'prod-winter-18',
    name: 'Kurzes Wollkleid von Prada',
    slug: 'robe-courte-en-laine-prada',
    price: 1700.00,
    description: 'Ein kurzes Kleid mit strukturierter Silhouette aus feiner Wolle, sinnbildlich für den schicken Minimalismus von Prada.',
    category: 'womens-clothing',
    images: ['robe-courte-en-laine-prada'],
    reviews: [],
  },
  {
    id: 'prod-winter-19',
    name: 'Langer Kaschmirmantel von Max Mara',
    slug: 'manteau-long-en-cachemire-max-mara',
    price: 4800.00,
    description: "Der ikonische 'Manuela'-Mantel von Max Mara aus reinem Kaschmir, ein zeitloses Stück von absoluter Eleganz.",
    category: 'womens-clothing',
    images: ['manteau-long-en-cachemire-max-mara'],
    reviews: [],
  },
  {
    id: 'prod-winter-20',
    name: 'Kurze Steppjacke von Moncler',
    slug: 'veste-courte-matelassee-moncler',
    price: 990.00,
    description: 'Eine kurze, gesteppte Jacke, die Moncler-Performance mit einer femininen und modernen Silhouette verbindet.',
    category: 'womens-clothing',
    images: ['veste-courte-matelassee-moncler'],
    reviews: [],
  },
  {
    id: 'prod-winter-21',
    name: 'Oversize-Zopfmusterpullover von Chloé',
    slug: 'pull-oversize-torsade-chloe',
    price: 1200.00,
    description: 'Ein Oversize-Pullover aus dickem Zopfstrick, der die bohèmehafte Romantik des Hauses Chloé verkörpert.',
    category: 'womens-clothing',
    images: ['pull-oversize-torsade-chloe'],
    reviews: [],
  },
  {
    id: 'prod-winter-22',
    name: 'Woll-Bleistiftrock von Hugo Boss',
    slug: 'jupe-crayon-en-laine-hugo-boss',
    price: 350.00,
    description: 'Ein perfekt geschnittener Bleistiftrock aus Stretch-Wolle von Hugo Boss, unverzichtbar für eine professionelle Garderobe.',
    category: 'womens-clothing',
    images: ['jupe-crayon-en-laine-hugo-boss'],
    reviews: [],
  },
  {
    id: 'prod-winter-23',
    name: 'Langes Plisseekleid von Valentino',
    slug: 'robe-longue-plissee-valentino',
    price: 3900.00,
    description: 'Eine spektakuläre Kreation von Valentino: Dieses lange Kleid aus plissiertem Stoff schwebt bei jeder Bewegung.',
    category: 'womens-clothing',
    images: ['robe-longue-plissee-valentino'],
    reviews: [],
  },
  {
    id: 'prod-winter-24',
    name: 'Premium-Baumwollhemd von Burberry',
    slug: 'chemise-en-coton-premium-burberry',
    price: 450.00,
    description: 'Ein makelloses weißes Hemd aus Premium-Baumwolle, verfeinert mit dezenten Details wie dem ikonischen Tartan-Muster im Kragen.',
    category: 'womens-clothing',
    images: ['chemise-en-coton-premium-burberry'],
    reviews: [],
  },
  {
    id: 'prod-winter-25',
    name: 'Seiden-Wickelkleid von Diane von Furstenberg',
    slug: 'robe-portefeuille-en-soie-diane-von-furstenberg',
    price: 550.00,
    description: 'Das ikonische DVF-Wickelkleid aus Seidenjersey, ein Stück, das jeder Silhouette mit zeitloser Eleganz schmeichelt.',
    category: 'womens-clothing',
    images: ['robe-portefeuille-en-soie-diane-von-furstenberg'],
    reviews: [],
  },
  {
    id: 'prod-winter-26',
    name: 'Anzughose von Dior für Damen',
    slug: 'pantalon-tailleur-dior-femme',
    price: 1200.00,
    description: 'Eine Anzughose mit tadellosem Schnitt, die das Savoir-faire und die Eleganz des Hauses Dior widerspiegelt.',
    category: 'womens-clothing',
    images: ['pantalon-tailleur-dior-femme'],
    reviews: [],
  },
  {
    id: 'prod-winter-27',
    name: 'U-Boot-Ausschnitt-Pullover von Ralph Lauren',
    slug: 'pull-col-bateau-ralph-lauren',
    price: 320.00,
    description: 'Ein klassischer Pullover mit U-Boot-Ausschnitt aus feinem Strick, ein vielseitiges und schickes Stück von Ralph Lauren.',
    category: 'womens-clothing',
    images: ['pull-col-bateau-ralph-lauren'],
    reviews: [],
  },
  {
    id: 'prod-winter-28',
    name: 'Langer Kaschmir-Cardigan von Brunello Cucinelli',
    slug: 'cardigan-long-en-cachemire-brunello-cucinelli',
    price: 2900.00,
    description: 'Die Quintessenz des lässigen Luxus. Dieser lange und umhüllende Cardigan ist aus feinstem Kaschmir gestrickt.',
    category: 'womens-clothing',
    images: ['cardigan-long-en-cachemire-brunello-cucinelli'],
    reviews: [],
  },
  {
    id: 'prod-winter-29',
    name: 'Asymmetrisches Kleid von Givenchy',
    slug: 'robe-asymetrique-givenchy',
    price: 2100.00,
    description: 'Ein schwarzes Kleid mit kühnem asymmetrischem Schnitt, sinnbildlich für den architektonischen und modernen Stil von Givenchy.',
    category: 'womens-clothing',
    images: ['robe-asymetrique-givenchy'],
    reviews: [],
  },
  {
    id: 'prod-winter-30',
    name: 'Satinbluse von Stella McCartney',
    slug: 'blouse-satinee-stella-mccartney',
    price: 650.00,
    description: 'Eine fließende und elegante Bluse aus nachhaltigem Seidensatin, perfekt für einen anspruchsvollen und bewussten Look.',
    category: 'womens-clothing',
    images: ['blouse-satinee-stella-mccartney'],
    reviews: [],
  },
  {
    id: 'prod-winter-31',
    name: 'Jumpsuit von Balenciaga',
    slug: 'combinaison-pantalon-balenciaga',
    price: 2400.00,
    description: 'Ein starkes Stück mit avantgardistischem Design. Dieser Balenciaga-Jumpsuit formt eine moderne und kraftvolle Silhouette.',
    category: 'womens-clothing',
    images: ['combinaison-pantalon-balenciaga'],
    reviews: [],
  },
  {
    id: 'prod-winter-32',
    name: 'Oversize-Mantel von Acne Studios',
    slug: 'manteau-oversize-acne-studios',
    price: 1100.00,
    description: 'Ein Oversize-Mantel aus doppelseitiger Wolle, charakteristisch für den coolen und minimalistischen Stil von Acne Studios.',
    category: 'womens-clothing',
    images: ['manteau-oversize-acne-studios'],
    reviews: [],
  },
  {
    id: 'prod-winter-33',
    name: 'Kaschmir-Pulloverkleid von Max Mara',
    slug: 'robe-pull-en-cachemire-max-mara',
    price: 1300.00,
    description: 'Dieses Pulloverkleid aus reinem Kaschmir vereint Komfort und Eleganz und ist ein luxuriöses und gemütliches Stück für den Winter.',
    category: 'womens-clothing',
    images: ['robe-pull-en-cachemire-max-mara'],
    reviews: [],
  },
  {
    id: 'prod-winter-34',
    name: 'Lederhose von Saint Laurent',
    slug: 'pantalon-en-cuir-saint-laurent',
    price: 2800.00,
    description: 'Eine Skinny-Hose aus Stretch-Lammleder, ein ikonisches Stück aus der rockigen und schicken Garderobe von Saint Laurent.',
    category: 'womens-clothing',
    images: ['pantalon-en-cuir-saint-laurent'],
    reviews: [],
  },
  {
    id: 'prod-winter-35',
    name: 'Plissierter Midirock von Valentino',
    slug: 'jupe-plissee-midi-valentino',
    price: 1800.00,
    description: 'Ein Midirock mit zartem Sonnenplissee, der bei jedem Schritt anmutig mitschwingt. Ein ikonisches Stück von Valentino.',
    category: 'womens-clothing',
    images: ['jupe-plissee-midi-valentino'],
    reviews: [],
  },
  {
    id: 'prod-winter-36',
    name: 'T-Shirt mit gesticktem Gucci-Logo',
    slug: 't-shirt-brode-logo-gucci',
    price: 550.00,
    description: 'Ein T-Shirt aus hochwertiger Baumwolle, veredelt mit dem gestickten Gucci-Logo für einen Hauch von lässigem Luxus.',
    category: 'womens-clothing',
    images: ['t-shirt-brode-logo-gucci'],
    reviews: [],
  },
  {
    id: 'prod-winter-37',
    name: 'U-Boot-Ausschnitt-Pullover mit Ballonärmeln von Chloé',
    slug: 'pull-col-bateau-manches-ballon-chloe',
    price: 950.00,
    description: 'Ein romantischer Pullover mit elegantem U-Boot-Ausschnitt und voluminösen Ballonärmeln, typisch für den Chloé-Stil.',
    category: 'womens-clothing',
    images: ['pull-col-bateau-manches-ballon-chloe'],
    reviews: [],
  },
  {
    id: 'prod-winter-38',
    name: 'Oversize-Hemdkleid von Balenciaga',
    slug: 'robe-chemise-oversize-balenciaga',
    price: 1250.00,
    description: 'Ein Hemdkleid mit kühnem Oversize-Schnitt für einen dekonstruierten und konzeptionellen Look von Balenciaga.',
    category: 'womens-clothing',
    images: ['robe-chemise-oversize-balenciaga'],
    reviews: [],
  },
  {
    id: 'prod-winter-39',
    name: 'Palazzo-Hose aus Wolle von Max Mara',
    slug: 'pantalon-palazzo-en-laine-max-mara',
    price: 750.00,
    description: 'Eine weite und fließende Palazzo-Hose aus Schurwolle, die die Silhouette mit spektakulärer Eleganz verlängert.',
    category: 'womens-clothing',
    images: ['pantalon-palazzo-en-laine-max-mara'],
    reviews: [],
  },
  {
    id: 'prod-winter-40',
    name: 'Satin-Blazer von Saint Laurent',
    slug: 'blazer-satin-saint-laurent',
    price: 2600.00,
    description: 'Inspiriert vom Smoking bietet dieser Blazer aus Duchesse-Satin einen nächtlichen und ultra-raffinierten Look.',
    category: 'womens-clothing',
    images: ['blazer-satin-saint-laurent'],
    reviews: [],
  },
  {
    id: 'prod-winter-41',
    name: 'Langes Samtkleid von Valentino',
    slug: 'robe-longue-en-velours-valentino',
    price: 4500.00,
    description: 'Ein prächtiges Abendkleid aus Seidensamt, opulent und doch von großer Linienreinheit.',
    category: 'womens-clothing',
    images: ['robe-longue-en-velours-valentino'],
    reviews: [],
  },
];


// --- Data-fetching functions ---

export function getProductsByCategory(categorySlug: string, limit?: number, excludeId?: string): Product[] {
  let filteredProducts: Product[];

  if (categorySlug === 'all') {
    filteredProducts = products;
  } else {
    filteredProducts = products.filter((p) => p.category === categorySlug);
  }

  if (excludeId) {
    filteredProducts = filteredProducts.filter((p) => p.id !== excludeId);
  }
  
  if (limit) {
    return filteredProducts.slice(0, limit);
  }

  return filteredProducts;
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getFeaturedProducts(limit: number = 4): Product[] {
    const winterProducts = products.filter(p => p.category === 'winter-clothing' || p.name.toLowerCase().includes('winter') || p.name.toLowerCase().includes('mantel') || p.name.toLowerCase().includes('pullover'));
    return winterProducts.slice(0, limit);
}
