import type { Product, Category } from './types';

export const categories: Category[] = [
  { id: 'cat-1', name: 'Herrenbekleidung', name_fr: 'Vêtements Homme', slug: 'mens-clothing', imageId: 'mens-category' },
  { id: 'cat-2', name: 'Damenbekleidung', name_fr: 'Vêtements Femme', slug: 'womens-clothing', imageId: 'womens-category' },
  { id: 'cat-3', name: 'Accessoires', name_fr: 'Accessoires', slug: 'accessories', imageId: 'accessories-category' },
  { id: 'cat-5', name: 'Schuhe', name_fr: 'Chaussures', slug: 'shoes', imageId: 'shoes-category' },
  { id: 'cat-4', name: 'Winterkleidung', name_fr: 'Vêtements d\'hiver', slug: 'winter-clothing', imageId: 'winter-category' },
];

export const products: Product[] = [
  // Winter Wear - Men
  {
    id: 'prod-winter-1',
    name: 'Langer Wollmantel von Hugo Boss',
    name_fr: 'Manteau Long en Laine Hugo Boss',
    slug: 'manteau-long-laine-hugo-boss',
    price: 799.00,
    description: 'Ein klassischer langer Mantel aus reiner Schurwolle, der Wärme und eine tadellos elegante Silhouette von Hugo Boss bietet.',
    description_fr: 'Un manteau long classique en pure laine vierge qui offre chaleur et une silhouette impeccablement élégante par Hugo Boss.',
    category: 'winter-clothing',
    images: ['manteau-long-laine-hugo-boss'],
    reviews: [],
  },
  {
    id: 'prod-winter-2',
    name: 'Gesteppte Daunenjacke von Moncler',
    name_fr: 'Doudoune Matelassée Moncler',
    slug: 'doudoune-matelassee-moncler',
    price: 1250.00,
    description: 'Die ikonische Daunenjacke von Moncler, die technische Leistung und alpinen Stil für optimalen Kälteschutz vereint.',
    description_fr: 'L\'emblématique doudoune Moncler, alliant performance technique et style alpin pour une protection optimale contre le froid.',
    category: 'winter-clothing',
    images: ['doudoune-matelassee-moncler'],
    reviews: [],
  },
  {
    id: 'prod-winter-3',
    name: 'Arctic Parka von Canada Goose',
    name_fr: 'Parka Arctic Canada Goose',
    slug: 'parka-arctic-canada-goose',
    price: 1150.00,
    description: 'Entwickelt für die extremsten Klimazonen, ist der Arctic Parka von Canada Goose der Gipfel an Wärme und Haltbarkeit.',
    description_fr: 'Conçu pour les climats les plus extrêmes, le parka Arctic de Canada Goose est le summum de la chaleur et de la durabilité.',
    category: 'winter-clothing',
    images: ['parka-arctic-canada-goose'],
    reviews: [],
  },
  {
    id: 'prod-winter-4',
    name: 'Kaschmirmantel von Loro Piana für Herren',
    name_fr: 'Manteau en Cachemire Loro Piana pour Homme',
    slug: 'manteau-cachemire-loro-piana-homme',
    price: 4500.00,
    description: 'Luxus in seiner reinsten Form. Dieser doppelseitige Kaschmirmantel von Loro Piana ist von unvergleichlicher Weichheit und Wärme.',
    description_fr: 'Le luxe à l\'état pur. Ce manteau en cachemire double face de Loro Piana est d\'une douceur et d\'une chaleur inégalées.',
    category: 'mens-clothing',
    images: ['manteau-cachemire-loro-piana-homme'],
    reviews: [],
  },
  {
    id: 'prod-winter-5',
    name: 'Shearling-Blouson von Saint Laurent',
    name_fr: 'Blouson en Shearling Saint Laurent',
    slug: 'blouson-shearling-saint-laurent',
    price: 4800.00,
    description: 'Ein kühner Fliegerblouson aus gewachsenem Lammfell von Saint Laurent für einen rockigen und luxuriösen Stil.',
    description_fr: 'Un audacieux blouson aviateur en peau de mouton retournée par Saint Laurent pour un style rock et luxueux.',
    category: 'mens-clothing',
    images: ['blouson-shearling-saint-laurent'],
    reviews: [],
  },
  {
    id: 'prod-winter-6',
    name: 'Rollkragenpullover aus Merinowolle von Paul Smith',
    name_fr: 'Pull à Col Roulé en Laine Mérinos Paul Smith',
    slug: 'pull-col-roule-laine-merinos-paul-smith',
    price: 350.00,
    description: 'Ein unverzichtbares Winter-Basic: Dieser Rollkragenpullover aus feiner Merinowolle von Paul Smith ist ebenso weich wie vielseitig.',
    description_fr: 'Un basique hivernal essentiel, ce pull à col roulé en fine laine mérinos de Paul Smith est aussi doux que polyvalent.',
    category: 'mens-clothing',
    images: ['pull-col-roule-laine-merinos-paul-smith'],
    reviews: [],
  },
  {
    id: 'prod-winter-7',
    name: 'Gefüttertes Überhemd von Acne Studios für Herren',
    name_fr: 'Surchemise Doublée Acne Studios pour Homme',
    slug: 'surchemise-doublee-acne-studios-homme',
    price: 420.00,
    description: 'Das gefütterte Wollflanell-Überhemd von Acne Studios, perfekt für Lagenlooks in der Übergangszeit mit skandinavischem Touch.',
    description_fr: 'La surchemise en flanelle de laine doublée d\'Acne Studios, parfaite pour les superpositions de mi-saison avec une touche scandinave.',
    category: 'mens-clothing',
    images: ['surchemise-doublee-acne-studios-homme'],
    reviews: [],
  },
  {
    id: 'prod-winter-8',
    name: 'Ärmellose Daunenjacke von Polo Ralph Lauren',
    name_fr: 'Doudoune Sans Manches Polo Ralph Lauren',
    slug: 'doudoune-sans-manche-polo-ralph-lauren',
    price: 250.00,
    description: 'Leicht und praktisch ist diese ärmellose Daunenjacke ein Klassiker von Polo Ralph Lauren, ideal über einem Pullover oder unter einem Mantel.',
    description_fr: 'Légère et pratique, cette doudoune sans manches est un classique de Polo Ralph Lauren, idéale sur un pull ou sous un manteau.',
    category: 'winter-clothing',
    images: ['doudoune-sans-manche-polo-ralph-lauren'],
    reviews: [],
  },
  {
    id: 'prod-winter-9',
    name: 'Doppelreihiger Trenchcoat von Burberry',
    name_fr: 'Trench-Coat Double Boutonnage Burberry',
    slug: 'manteau-trench-double-burberry',
    price: 1990.00,
    description: 'Der ikonische Trenchcoat von Burberry. Ein zeitloses und wetterfestes Stück, Symbol britischer Eleganz.',
    description_fr: 'L\'iconique trench-coat de Burberry. Une pièce intemporelle et résistante aux intempéries, symbole de l\'élégance britannique.',
    category: 'winter-clothing',
    images: ['manteau-trench-double-burberry'],
    reviews: [],
  },
  {
    id: 'prod-winter-10',
    name: 'Dicker Zopfmusterpullover von Dior Homme',
    name_fr: 'Pull Épais à Torsades Dior Homme',
    slug: 'pull-torsade-epais-dior-homme',
    price: 1100.00,
    description: 'Ein reich texturierter Pullover aus Wolle und Kaschmir, verziert mit klassischen Zopfmustern. Ein Meisterstück von Dior.',
    description_fr: 'Un pull richement texturé en laine et cachemire, orné de torsades classiques. Une pièce maîtresse de Dior.',
    category: 'mens-clothing',
    images: ['pull-torsade-epais-dior-homme'],
    reviews: [],
  },
  {
    id: 'prod-winter-11',
    name: 'Wasserdichte technische Jacke der TNF Black Series',
    name_fr: 'Veste Technique Imperméable TNF Black Series',
    slug: 'veste-technique-impermeable-tnf-black-series',
    price: 650.00,
    description: 'Aus der High-End-Linie von The North Face kombiniert diese Jacke futuristisches Design mit maximalem Schutz vor den Elementen.',
    description_fr: 'Issue de la ligne haut de gamme de The North Face, cette veste combine un design futuriste avec une protection maximale contre les éléments.',
    category: 'winter-clothing',
    images: ['veste-technique-impermeable-tnf-black-series'],
    reviews: [],
  },
  // Winter Wear - Women
  {
    id: 'prod-winter-12',
    name: 'Seiden-Midikleid von Gucci',
    name_fr: 'Robe Midi en Soie Gucci',
    slug: 'robe-midi-en-soie-gucci',
    price: 2500.00,
    description: 'Ein Midikleid aus Seiden-Crêpe von Gucci, verziert mit einem kühnen Druck für maximale Eleganz.',
    description_fr: 'Une robe midi en crêpe de soie par Gucci, ornée d\'un imprimé audacieux pour une élégance maximale.',
    category: 'womens-clothing',
    images: ['robe-midi-en-soie-gucci'],
    reviews: [],
  },
  {
    id: 'prod-winter-13',
    name: 'Doppelreihiger Blazer von Balmain',
    name_fr: 'Blazer Croisé Balmain',
    slug: 'blazer-croise-balmain',
    price: 2200.00,
    description: 'Der ikonische doppelreihige Balmain-Blazer mit seinen goldenen Knöpfen, ein starkes Stück, das die Silhouette kühn strukturiert.',
    description_fr: 'L\'iconique blazer croisé Balmain avec ses boutons dorés, une pièce forte qui structure la silhouette avec audace.',
    category: 'womens-clothing',
    images: ['blazer-croise-balmain'],
    reviews: [],
  },
  {
    id: 'prod-winter-14',
    name: 'Kaschmir-Rollkragenpullover von Loro Piana für Damen',
    name_fr: 'Pull à Col Roulé en Cachemire Loro Piana pour Femme',
    slug: 'pull-col-roule-cachemire-loro-piana-femme',
    price: 1800.00,
    description: 'Die Quintessenz von Luxus und Komfort. Dieser Rollkragenpullover von Loro Piana aus reinem Kaschmir ist wie eine zweite Haut.',
    description_fr: 'La quintessence du luxe et du confort. Ce pull à col roulé de Loro Piana en pur cachemire est comme une seconde peau.',
    category: 'womens-clothing',
    images: ['pull-col-roule-cachemire-loro-piana-femme'],
    reviews: [],
  },
  {
    id: 'prod-winter-15',
    name: 'Weite Wollhose von Max Mara',
    name_fr: 'Pantalon Large en Laine Max Mara',
    slug: 'pantalon-large-en-laine-max-mara',
    price: 650.00,
    description: 'Eine weit geschnittene Hose mit perfekter Passform aus fließender Wolle von Max Mara für einen schicken und lässigen Look.',
    description_fr: 'Un pantalon large à la coupe parfaite en laine fluide par Max Mara pour un look chic et décontracté.',
    category: 'womens-clothing',
    images: ['pantalon-large-en-laine-max-mara'],
    reviews: [],
  },
  {
    id: 'prod-winter-16',
    name: 'Premium Slim-Jeans von Diesel',
    name_fr: 'Jean Slim Premium Diesel',
    slug: 'jean-slim-premium-diesel',
    price: 280.00,
    description: 'Eine Slim-Jeans mit perfekter Passform und dezenter Waschung aus hochwertigem Denim von Diesel.',
    description_fr: 'Un jean slim à la coupe parfaite et au délavage subtil en denim de haute qualité par Diesel.',
    category: 'womens-clothing',
    images: ['jean-slim-premium-diesel'],
    reviews: [],
  },
  {
    id: 'prod-winter-17',
    name: 'Bedruckte Seidenbluse von Saint Laurent',
    name_fr: 'Chemisier en Soie Imprimée Saint Laurent',
    slug: 'chemisier-en-soie-imprimee-saint-laurent',
    price: 1350.00,
    description: 'Eleganz und Modernität treffen in dieser fließenden Seidenbluse mit exklusivem Saint Laurent-Druck aufeinander.',
    description_fr: 'Élégance et modernité se rencontrent dans ce chemisier fluide en soie à l\'imprimé exclusif Saint Laurent.',
    category: 'womens-clothing',
    images: ['chemisier-en-soie-imprimee-saint-laurent'],
    reviews: [],
  },
  {
    id: 'prod-winter-18',
    name: 'Kurzes Wollkleid von Prada',
    name_fr: 'Robe Courte en Laine Prada',
    slug: 'robe-courte-en-laine-prada',
    price: 1700.00,
    description: 'Ein kurzes Kleid mit strukturierter Silhouette aus feiner Wolle, sinnbildlich für den schicken Minimalismus von Prada.',
    description_fr: 'Une robe courte à la silhouette structurée en laine fine, emblématique du minimalisme chic de Prada.',
    category: 'womens-clothing',
    images: ['robe-courte-en-laine-prada'],
    reviews: [],
  },
  {
    id: 'prod-winter-19',
    name: 'Langer Kaschmirmantel von Max Mara',
    name_fr: 'Manteau Long en Cachemire Max Mara',
    slug: 'manteau-long-en-cachemire-max-mara',
    price: 4800.00,
    description: "Der ikonische 'Manuela'-Mantel von Max Mara aus reinem Kaschmir, ein zeitloses Stück von absoluter Eleganz.",
    description_fr: "L'iconique manteau 'Manuela' de Max Mara en pur cachemire, une pièce intemporelle d\'une élégance absolue.",
    category: 'womens-clothing',
    images: ['manteau-long-en-cachemire-max-mara'],
    reviews: [],
  },
  {
    id: 'prod-winter-20',
    name: 'Kurze Steppjacke von Moncler',
    name_fr: 'Veste Courte Matelassée Moncler',
    slug: 'veste-courte-matelassee-moncler',
    price: 990.00,
    description: 'Eine kurze, gesteppte Jacke, die Moncler-Performance mit einer femininen und modernen Silhouette verbindet.',
    description_fr: 'Une veste courte matelassée qui allie la performance Moncler à une silhouette féminine et moderne.',
    category: 'womens-clothing',
    images: ['veste-courte-matelassee-moncler'],
    reviews: [],
  },
  {
    id: 'prod-winter-21',
    name: 'Oversize-Zopfmusterpullover von Chloé',
    name_fr: 'Pull Oversize à Torsades Chloé',
    slug: 'pull-oversize-torsade-chloe',
    price: 1200.00,
    description: 'Ein Oversize-Pullover aus dickem Zopfstrick, der die bohèmehafte Romantik des Hauses Chloé verkörpert.',
    description_fr: 'Un pull oversize en grosse maille torsadée qui incarne le romantisme bohème de la maison Chloé.',
    category: 'womens-clothing',
    images: ['pull-oversize-torsade-chloe'],
    reviews: [],
  },
  {
    id: 'prod-winter-22',
    name: 'Woll-Bleistiftrock von Hugo Boss',
    name_fr: 'Jupe Crayon en Laine Hugo Boss',
    slug: 'jupe-crayon-en-laine-hugo-boss',
    price: 350.00,
    description: 'Ein perfekt geschnittener Bleistiftrock aus Stretch-Wolle von Hugo Boss, unverzichtbar für eine professionelle Garderobe.',
    description_fr: 'Une jupe crayon parfaitement coupée en laine stretch par Hugo Boss, indispensable pour une garde-robe professionnelle.',
    category: 'womens-clothing',
    images: ['jupe-crayon-en-laine-hugo-boss'],
    reviews: [],
  },
  {
    id: 'prod-winter-23',
    name: 'Langes Plisseekleid von Valentino',
    name_fr: 'Robe Longue Plissée Valentino',
    slug: 'robe-longue-plissee-valentino',
    price: 3900.00,
    description: 'Eine spektakuläre Kreation von Valentino: Dieses lange Kleid aus plissiertem Stoff schwebt bei jeder Bewegung.',
    description_fr: 'Une création spectaculaire de Valentino, cette longue robe en tissu plissé flotte à chaque mouvement.',
    category: 'womens-clothing',
    images: ['robe-longue-plissee-valentino'],
    reviews: [],
  },
  {
    id: 'prod-winter-24',
    name: 'Premium-Baumwollhemd von Burberry',
    name_fr: 'Chemise en Coton Premium Burberry',
    slug: 'chemise-en-coton-premium-burberry',
    price: 450.00,
    description: 'Ein makelloses weißes Hemd aus Premium-Baumwolle, verfeinert mit dezenten Details wie dem ikonischen Tartan-Muster im Kragen.',
    description_fr: 'Une chemise blanche impeccable en coton premium, rehaussée de détails discrets comme le tartan iconique à l\'intérieur du col.',
    category: 'womens-clothing',
    images: ['chemise-en-coton-premium-burberry'],
    reviews: [],
  },
  {
    id: 'prod-winter-25',
    name: 'Seiden-Wickelkleid von Diane von Furstenberg',
    name_fr: 'Robe Portefeuille en Soie Diane von Furstenberg',
    slug: 'robe-portefeuille-en-soie-diane-von-furstenberg',
    price: 550.00,
    description: 'Das ikonische DVF-Wickelkleid aus Seidenjersey, ein Stück, das jeder Silhouette mit zeitloser Eleganz schmeichelt.',
    description_fr: 'L\'iconique robe portefeuille DVF en jersey de soie, une pièce qui flatte toutes les silhouettes avec une élégance intemporelle.',
    category: 'womens-clothing',
    images: ['robe-portefeuille-en-soie-diane-von-furstenberg'],
    reviews: [],
  },
  {
    id: 'prod-winter-26',
    name: 'Anzughose von Dior für Damen',
    name_fr: 'Pantalon de Tailleur Dior pour Femme',
    slug: 'pantalon-tailleur-dior-femme',
    price: 1200.00,
    description: 'Eine Anzughose mit tadellosem Schnitt, die das Savoir-faire und die Eleganz des Hauses Dior widerspiegelt.',
    description_fr: 'Un pantalon de tailleur à la coupe impeccable, qui reflète le savoir-faire et l\'élégance de la maison Dior.',
    category: 'womens-clothing',
    images: ['pantalon-tailleur-dior-femme'],
    reviews: [],
  },
  {
    id: 'prod-winter-27',
    name: 'U-Boot-Ausschnitt-Pullover von Ralph Lauren',
    name_fr: 'Pull à Col Bateau Ralph Lauren',
    slug: 'pull-col-bateau-ralph-lauren',
    price: 320.00,
    description: 'Ein klassischer Pullover mit U-Boot-Ausschnitt aus feinem Strick, ein vielseitiges und schickes Stück von Ralph Lauren.',
    description_fr: 'Un pull classique à encolure bateau en maille fine, une pièce polyvalente et chic de Ralph Lauren.',
    category: 'womens-clothing',
    images: ['pull-col-bateau-ralph-lauren'],
    reviews: [],
  },
  {
    id: 'prod-winter-28',
    name: 'Langer Kaschmir-Cardigan von Brunello Cucinelli',
    name_fr: 'Long Cardigan en Cachemire Brunello Cucinelli',
    slug: 'cardigan-long-en-cachemire-brunello-cucinelli',
    price: 2900.00,
    description: 'Die Quintessenz des lässigen Luxus. Dieser lange und umhüllende Cardigan ist aus feinstem Kaschmir gestrickt.',
    description_fr: 'La quintessence du luxe décontracté. Ce long et enveloppant cardigan est tricoté dans le plus fin des cachemires.',
    category: 'womens-clothing',
    images: ['cardigan-long-en-cachemire-brunello-cucinelli'],
    reviews: [],
  },
  {
    id: 'prod-winter-29',
    name: 'Asymmetrisches Kleid von Givenchy',
    name_fr: 'Robe Asymétrique Givenchy',
    slug: 'robe-asymetrique-givenchy',
    price: 2100.00,
    description: 'Ein schwarzes Kleid mit kühnem asymmetrischem Schnitt, sinnbildlich für den architektonischen und modernen Stil von Givenchy.',
    description_fr: 'Une robe noire à la coupe asymétrique audacieuse, emblématique du style architectural et moderne de Givenchy.',
    category: 'womens-clothing',
    images: ['robe-asymetrique-givenchy'],
    reviews: [],
  },
  {
    id: 'prod-winter-30',
    name: 'Satinbluse von Stella McCartney',
    name_fr: 'Blouse Satinée Stella McCartney',
    slug: 'blouse-satinee-stella-mccartney',
    price: 650.00,
    description: 'Eine fließende und elegante Bluse aus nachhaltigem Seidensatin, perfekt für einen anspruchsvollen und bewussten Look.',
    description_fr: 'Une blouse fluide et élégante en satin de soie durable, parfaite pour un look sophistiqué et conscient.',
    category: 'womens-clothing',
    images: ['blouse-satinee-stella-mccartney'],
    reviews: [],
  },
  {
    id: 'prod-winter-31',
    name: 'Jumpsuit von Balenciaga',
    name_fr: 'Combinaison-Pantalon Balenciaga',
    slug: 'combinaison-pantalon-balenciaga',
    price: 2400.00,
    description: 'Ein starkes Stück mit avantgardistischem Design. Dieser Balenciaga-Jumpsuit formt eine moderne und kraftvolle Silhouette.',
    description_fr: 'Une pièce forte au design avant-gardiste. Cette combinaison-pantalon Balenciaga sculpte une silhouette moderne et puissante.',
    category: 'womens-clothing',
    images: ['combinaison-pantalon-balenciaga'],
    reviews: [],
  },
  {
    id: 'prod-winter-32',
    name: 'Oversize-Mantel von Acne Studios',
    name_fr: 'Manteau Oversize Acne Studios',
    slug: 'manteau-oversize-acne-studios',
    price: 1100.00,
    description: 'Ein Oversize-Mantel aus doppelseitiger Wolle, charakteristisch für den coolen und minimalistischen Stil von Acne Studios.',
    description_fr: 'Un manteau oversize en laine double face, caractéristique du style cool et minimaliste d\'Acne Studios.',
    category: 'womens-clothing',
    images: ['manteau-oversize-acne-studios'],
    reviews: [],
  },
  {
    id: 'prod-winter-33',
    name: 'Kaschmir-Pulloverkleid von Max Mara',
    name_fr: 'Robe-Pull en Cachemire Max Mara',
    slug: 'robe-pull-en-cachemire-max-mara',
    price: 1300.00,
    description: 'Dieses Pulloverkleid aus reinem Kaschmir vereint Komfort und Eleganz und ist ein luxuriöses und gemütliches Stück für den Winter.',
    description_fr: 'Alliant confort et élégance, cette robe-pull en pur cachemire est une pièce luxueuse et confortable pour l\'hiver.',
    category: 'womens-clothing',
    images: ['robe-pull-en-cachemire-max-mara'],
    reviews: [],
  },
  {
    id: 'prod-winter-34',
    name: 'Lederhose von Saint Laurent',
    name_fr: 'Pantalon en Cuir Saint Laurent',
    slug: 'pantalon-en-cuir-saint-laurent',
    price: 2800.00,
    description: 'Eine Skinny-Hose aus Stretch-Lammleder, ein ikonisches Stück aus der rockigen und schicken Garderobe von Saint Laurent.',
    description_fr: 'Un pantalon skinny en cuir d\'agneau stretch, une pièce iconique du vestiaire rock et chic de Saint Laurent.',
    category: 'womens-clothing',
    images: ['pantalon-en-cuir-saint-laurent'],
    reviews: [],
  },
  {
    id: 'prod-winter-35',
    name: 'Plissierter Midirock von Valentino',
    name_fr: 'Jupe Plissée Midi Valentino',
    slug: 'jupe-plissee-midi-valentino',
    price: 1800.00,
    description: 'Ein Midirock mit zartem Sonnenplissee, der bei jedem Schritt anmutig mitschwingt. Ein ikonisches Stück von Valentino.',
    description_fr: 'Une jupe midi au délicat plissé soleil qui ondule gracieusement à chaque pas. Une pièce iconique de Valentino.',
    category: 'womens-clothing',
    images: ['jupe-plissee-midi-valentino'],
    reviews: [],
  },
  {
    id: 'prod-winter-36',
    name: 'T-Shirt mit gesticktem Gucci-Logo',
    name_fr: 'T-Shirt Brodé Logo Gucci',
    slug: 't-shirt-brode-logo-gucci',
    price: 550.00,
    description: 'Ein T-Shirt aus hochwertiger Baumwolle, veredelt mit dem gestickten Gucci-Logo für einen Hauch von lässigem Luxus.',
    description_fr: 'Un t-shirt en coton de qualité supérieure, rehaussé du logo Gucci brodé pour une touche de luxe décontracté.',
    category: 'womens-clothing',
    images: ['t-shirt-brode-logo-gucci'],
    reviews: [],
  },
  {
    id: 'prod-winter-37',
    name: 'U-Boot-Ausschnitt-Pullover mit Ballonärmeln von Chloé',
    name_fr: 'Pull à Col Bateau et Manches Ballon Chloé',
    slug: 'pull-col-bateau-manches-ballon-chloe',
    price: 950.00,
    description: 'Ein romantischer Pullover mit elegantem U-Boot-Ausschnitt und voluminösen Ballonärmeln, typisch für den Chloé-Stil.',
    description_fr: 'Un pull romantique avec une élégante encolure bateau et des manches ballon volumineuses, typique du style Chloé.',
    category: 'womens-clothing',
    images: ['pull-col-bateau-manches-ballon-chloe'],
    reviews: [],
  },
  {
    id: 'prod-winter-38',
    name: 'Oversize-Hemdkleid von Balenciaga',
    name_fr: 'Robe-Chemise Oversize Balenciaga',
    slug: 'robe-chemise-oversize-balenciaga',
    price: 1250.00,
    description: 'Ein Hemdkleid mit kühnem Oversize-Schnitt für einen dekonstruierten und konzeptionellen Look von Balenciaga.',
    description_fr: 'Une robe-chemise à la coupe oversize audacieuse pour un look déconstruit et conceptuel par Balenciaga.',
    category: 'womens-clothing',
    images: ['robe-chemise-oversize-balenciaga'],
    reviews: [],
  },
  {
    id: 'prod-winter-39',
    name: 'Palazzo-Hose aus Wolle von Max Mara',
    name_fr: 'Pantalon Palazzo en Laine Max Mara',
    slug: 'pantalon-palazzo-en-laine-max-mara',
    price: 750.00,
    description: 'Eine weite und fließende Palazzo-Hose aus Schurwolle, die die Silhouette mit spektakulärer Eleganz verlängert.',
    description_fr: 'Un pantalon palazzo large et fluide en laine vierge qui allonge la silhouette avec une élégance spectaculaire.',
    category: 'womens-clothing',
    images: ['pantalon-palazzo-en-laine-max-mara'],
    reviews: [],
  },
  {
    id: 'prod-winter-40',
    name: 'Satin-Blazer von Saint Laurent',
    name_fr: 'Blazer en Satin Saint Laurent',
    slug: 'blazer-satin-saint-laurent',
    price: 2600.00,
    description: 'Inspiriert vom Smoking bietet dieser Blazer aus Duchesse-Satin einen nächtlichen und ultra-raffinierten Look.',
    description_fr: 'Inspiré du smoking, ce blazer en satin duchesse offre un look nocturne et ultra-raffiné.',
    category: 'womens-clothing',
    images: ['blazer-satin-saint-laurent'],
    reviews: [],
  },
  {
    id: 'prod-winter-41',
    name: 'Langes Samtkleid von Valentino',
    name_fr: 'Robe Longue en Velours Valentino',
    slug: 'robe-longue-en-velours-valentino',
    price: 4500.00,
    description: 'Ein prächtiges Abendkleid aus Seidensamt, opulent und doch von großer Linienreinheit.',
    description_fr: 'Une somptueuse robe de soirée en velours de soie, opulente mais d\'une grande pureté de ligne.',
    category: 'womens-clothing',
    images: ['robe-longue-en-velours-valentino'],
    reviews: [],
  },
];


// --- Data-fetching functions ---

export function getProductsByCategory(categorySlug: string, limit?: number, excludeId?: string): Product[] {
  let filteredProducts: Product[];

  if (categorySlug === 'all') {
    filteredProducts = products;
  } else {
    filteredProducts = products.filter((p) => p.category === categorySlug);
  }

  if (excludeId) {
    filteredProducts = filteredProducts.filter((p) => p.id !== excludeId);
  }
  
  if (limit) {
    return filteredProducts.slice(0, limit);
  }

  return filteredProducts;
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getFeaturedProducts(limit: number = 4): Product[] {
    const winterProducts = products.filter(p => p.category === 'winter-clothing' || p.name.toLowerCase().includes('winter') || p.name.toLowerCase().includes('mantel') || p.name.toLowerCase().includes('pullover'));
    return winterProducts.slice(0, limit);
}
